baseurl: https://nicole-brewer.github.io/long-tales-of-science
languageCode: en-us
title: Long Tales of Science
theme: castanet
googleAnalytics: ''
paginate: '9'
buildFuture: yes
taxonomies:
  category: categories
  series: series
  tag: tags
permalinks:
  about: /:filename/
  episode: /:filename/
Menu:
  Main:
    - identifier: about
      name: About
      url: /about
    - identifier: guests
      name: Guests
      url: /guest
    - identifier: upcoming
      name: Upcoming Episodes
      url: /upcoming
    - identifier: contact
      name: Contact
      url: /contact
    #- identifier: blog
    #  name: Blog
    #  url: /blog
params:
  android_subscribe: http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U
  authors:
    Nicole:
      bio: I am a software engineer in the Scientific Solutions Group within Research Computing at Purdue University. My primary contribution is to the NSF-funded science gateway, GeoEDF, for managing, sharing, analyzing, and visualizing geospacial data. I have also worked in a facilitation roll in a research lab where I implemented and recommended standard practices, training research scientists, wrote workflow-enabling tools, and deployed complex UIs in Jupyter. I'm passionate about improving the state of science through sustainable software practices, the treatment of software as first-class research objects, improved institutional support for research software engineers, and diversity and inclusion. Catch me conversing about these topics on the Long Tales of Science Podcast - a podcast about women in HPC!
      name: Nicole Brewer
      social:
        twitter: catch_me_coding
        homepage: https://nicole-brewer.com
        github: nicole-brewer
        #instagram:
        #pinterest
        #youtube
        
      thumbnail: img/host/nbrewer.jpg
  copyright_notice: Copyright 2022 [Nicole Brewer](https://nicole-brewer.com)
  description: Our mission is to expose and encourage women to pursue research and careers in high performance computing and computing-envabled fields. In this podcast, we interview women in HPC about their research, career paths, and what it means to be a woman in technology. Interviewees come from industry, academia, government, science, engineering, social science, and the humanities.
  disable_title_caps: 'true'
  disqusShortname: ''
  enable_jumbo: 'true'
  episode_number_prefix: 'Episode '
  episode_number_style: dash
  feed:
    copyright: Copyright 2020 Nicole Brewer
    itunes_author: Nicole Brewer
    itunes_first_sub_category: Software How-To
    itunes_image: https://github.com/nicole-brewer/long-tales-of-science/tree/main/static/img/my_logo.png
    itunes_owner_email: brewer36@purdue.edu
    itunes_owner_name: Nicole Brewer
    itunes_second_sub_category: Tech News
    itunes_subtitle: A podcast about women in high-performance computing
    itunes_summary: Our mission is to expose and encourage women to pursue research and careers in high performance computing and computing-envabled fields. In this podcast, we interview women in HPC about their research, career paths, and what it means to be a woman in technology. Interviewees come from industry, academia, government, science, engineering, social science, and the humanities.
    itunes_top_category: Technology
    language: en-us
  google_play_subscribe: https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuYXJyZXN0ZWRkZXZvcHMuY29tL2VwaXNvZGUvaW5kZXgueG1s
  itunes_subscribe: https://podcasts.apple.com/us/podcast/arrested-devops/id773888088?ign-mpt=uo%3D4&mt=2
  links:
    ado:
      name: Arrested DevOps
      url: https://www.arresteddevops.com
    ffs:
      name: Food Fight Show
      url: https://foodfightshow.org
    sdt:
      name: Software Defined Talk
      url: https://cote.io/podcasts/sdt/
  mailchimp_subscribe: //arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc
  mainSections: episode
  media_prefix: https://github.com/nicole-brewer/long-tales-of-science/blob/main/content/episode
  pocketcasts_subscribe: http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss
  podlove:
    subscribe_color: '#585e6c'
    subscribe_cover: img/my_logo.png
    subscribe_description: ''
    subscribe_feed_format: mp3
    subscribe_feed_type: audio
    subscribe_format: rectangle
    subscribe_language: de
    subscribe_size: medium
    subscribe_style: filled
    subscribe_subtitle: ''
    subscribe_title: ''
  realfavicongenerator:
    mask_icon_color: '#5bbad5'
    msapplication_tilecolor: '#2b5797'
    theme_color: '#ffffff'
  show_next_upcoming: 'true'
  site_layout: row
  site_theme: blue
  social:
    linkedin: https://www.linkedin.com/groups/12455312/
    twitter: https://twitter.com/longtalesofsci
  soundcloud_subscribe: http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss
  spotify_subscribe: https://open.spotify.com/show/...
  stitcher_subscribe: http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops
  #youtube_subscribe: https://www.youtube.com/arresteddevops?sub_confirmation=1
